---
version: "2"
plugins:
  duplication:
    enabled: true
    exclude_paths:
    - spec/
checks:
  method-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 10
exclude_patterns:
- spec/
